= anillo documentation
Jesús Espino García, <jespinog@gmail.com>
:toc: left
:numbered:
:source-highlighter: pygments
:pygments-style: friendly
:sectlinks:


== Introduction

_anillo_ is a nano framework inspired on ring and compojure.


== Project Maturity

Since _anillo_ is a young project there may be some API breakage.


== Install

This section covers the _anillo_ library installing process and its requirements.


=== Requirements

_anillo_ is tested with these platforms:

- Python 3.3
- Python 3.4


=== Pip

The simplest way to use _anillo_ in your project is to install it with *pip*:

[source, text]
----
pip install anillo==0.0.1
----

=== Get the Code

_anillo_ is open source and can be found on link:https://github.com/jespino/anillo[github].

You can clone the public repository with this command:

[source,text]
----
git clone https://github.com/jespino/anillo
----


== Getting started

TBD


== Advanced usage

TBD


== FAQ

TBD


== How to Contribute?

=== Philosophy

Five most important rules:

- Beautiful is better than ugly.
- Explicit is better than implicit.
- Simple is better than complex.
- Complex is better than complicated.
- Readability counts.

All contributions to _anillo_ should keep these important rules in mind.


=== Procedure

Just follow the following steps depending on the situation:

*Bugfix*:

- Fork the GitHub repo.
- Fix a bug/typo on a new branch.
- Make a pull-request to master.

*New feature*:

- Open new issue with the new feature proposal.
- If it is accepted, follow the same steps as "bugfix".


=== License

_anillo_ is licensed under BSD (2-Clause) license:

----
Copyright (c) 2015, Jesús Espino García <jespinog@gmail.com>

All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

* Redistributions of source code must retain the above copyright notice, this
  list of conditions and the following disclaimer.

* Redistributions in binary form must reproduce the above copyright notice,
  this list of conditions and the following disclaimer in the documentation
  and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
----
